language: java
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_522778301c96_key -iv $encrypted_522778301c96_iv
  -in ./.build/secrets/secrets.json.enc -out ./.build/secrets/decrypted/secrets.json -d
script: mvn clean package
